export const RECOMMEND_URL = '//qq-music-api.lwq945.site'
export const TOPLIST_URL = '//qq-music-api.lwq945.site/top'
export const HOTKEY_URL = '//qq-music-api.lwq945.site/gotHotkey'
export const SEARCH_URL = '//qq-music-api.lwq945.site/search'
export const LYRICS_URL = '//qq-music-api.lwq945.site/lyrics'