export const RECOMMEND_URL = 'https://qq-server-kfhdengskt.now.sh/'
export const TOPLIST_URL = 'https://qq-server-kfhdengskt.now.sh/top'
export const HOTKEY_URL = 'https://qq-server-kfhdengskt.now.sh/gotHotkey'
export const SEARCH_URL = 'https://qq-server-kfhdengskt.now.sh/search'
export const LYRICS_URL = 'https://qq-server-kfhdengskt.now.sh/lyrics'