export const RECOMMEND_URL = 'https://qq-music-api.lwq945.site'
export const TOPLIST_URL = 'https://qq-music-api.lwq945.site/top'
export const HOTKEY_URL = 'https://qq-music-api.lwq945.site/gotHotkey'
export const SEARCH_URL = 'https://qq-music-api.lwq945.site/search'
export const LYRICS_URL = 'https://qq-music-api.lwq945.site/lyrics'